### ISSUE TITLE
Install do nothing

### ISSUE THREAD

**Issue by kywan** [wadahiro/keycloak-discord#10]
I may be stupid but i try to install the extension but when i reaload my keycloak i cant find the discord option in Identity Providers... what i am doing wrong ? :/ did i  miss something ?

**Comment by havenotfear** [comment]
You might need to restart keycloak for it to deploy the .ear

**Comment by kywan** [comment]
> You might need to restart keycloak for it to deploy the .ear

yes i restart the docker of course, but still not Discord in my providers

**Comment by havenotfear** [comment]
I haven't tried this on docker but i have with the codecentric kubernetes plugin

First i created a config map from the file `kubectl create configmap config --from-file keycloak-discord-ear-0.3.1.ear`
Then used these options to mount the volume
```
extraVolumeMounts: |
  - name: "config"
    mountPath: "/opt/jboss/keycloak/standalone/deployments/keycloak-discord-ear-0.3.1.ear"
    subPath: "keycloak-discord-ear-0.3.1.ear"
extraVolumes: |
  - name: "config"
    configMap:
      name: "config"
```

For docker i would assume you would want to mount the ear and that option would look like `-v ./keycloak-discord-ear-0.3.1.ear:/opt/jboss/keycloak/standalone/deployments/keycloak-discord-ear-0.3.1.ear`
