### ISSUE TITLE
Keycloak 21

### ISSUE THREAD

**Issue by zelytra** [wadahiro/keycloak-discord#33]
Is it possible to update into keycloak 21+ ? I'm trying to install the latest version of your extensions. But it didn't show inside entity provider list : 
![image](https://github.com/wadahiro/keycloak-discord/assets/72125876/c35ce8e4-7533-4449-bb55-84856f45ee6a)

I'm deploying using docker here the configuration : 
```yml
version: '3.5'

services:

  postgres-keycloak:
    image: postgres:14.2-alpine
    container_name: ticketer-web-keycloak-postgres
    ports:
      - "9300:5432"
    environment:
      TZ: 'Europe/Paris'
      PGTZ: 'Europe/Paris'
      POSTGRES_DB: DiscordTicketerKeycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./psql-config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./psql-data/auth:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    container_name: ticketer-web-keycloak
    depends_on:
      - postgres-keycloak
    ports:
      - "9302:8080"
    volumes:
      - ./keycloak/config:/opt/keycloak/conf
      - ./keycloak/themes/histeria:/opt/keycloak/themes/histeria
      - ./keycloak/extensions:/opt/keycloak/providers
    command: start --optimized
    environment:
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_HOST: "0.0.0.0"
      KC_HTTP_RELATIVE_PATH: /auth
      DB_VENDOR: postgres
      KC_DB_URL_HOST: postgres-keycloak
      KC_PROXY: edge
      KC_DB_URL_DATABASE: DiscordTicketerKeycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    restart: unless-stopped

```
I can confirme you that the volume are weld setup, i check by accessing the container of keycloak and looking if it's inside the /opt/keycloak/providers folder.
